using System.Text;
using System.Text.Json;

namespace HireIQ.API.Services;

public class GroqService
{
    private readonly HttpClient _client;
    private readonly string _apiKey;
    private const string MODEL = "llama-3.3-70b-versatile";
    private const string API_URL = "https://api.groq.com/openai/v1/chat/completions";

    private const string SYSTEM_PROMPT = """
You are HireIQ, an expert AI HR assistant.

You specialize in:

1. RESUME SCREENING & SCORING:
   - Analyze resume vs job description
   - Give score out of 100
   - List strengths and skill gaps
   - Give clear Shortlist/Reject decision
   - Format: ## HireIQ Evaluation, Score: X/100

2. HR CONVERSATIONS:
   - Career guidance and roadmaps
   - Skill gap analysis
   - Salary insights (India market in LPA)
   - Interview preparation tips
   - Career transition advice

3. CANDIDATE SHORTLISTING:
   - Compare multiple candidates
   - Budget-aware ranking
   - Justify your selections clearly

4. RESUME BUILDING:
   - Generate COMPLETE professional HTML resume
   - Include CSS styling inline
   - Modern layout with sidebar or header
   - Skill tags, experience bullets
   - Footer: Generated by HireIQ
   - Make it ATS-friendly

Be professional, helpful, and concise.
Only mention HireIQ when asked who you are.
Never repeatedly mention your creator in responses.
""";

    public GroqService(IConfiguration config)
    {
        _apiKey = config["GroqSettings:ApiKey"] ??
                  Environment.GetEnvironmentVariable("GROQ_API_KEY") ?? "";
        _client = new HttpClient();
        _client.DefaultRequestHeaders.Add(
            "Authorization", $"Bearer {_apiKey}"
        );
    }

    public async Task<string> GenerateAsync(
        string userMessage,
        List<object>? history = null)
    {
        var messages = new List<object>
        {
            new { role = "system", content = SYSTEM_PROMPT }
        };

        if (history != null)
        {
            messages.AddRange(history.TakeLast(5));
        }

        messages.Add(new { role = "user", content = userMessage });

        var payload = new
        {
            model = MODEL,
            messages,
            max_tokens = 2048,
            temperature = 0.7
        };

        var json = JsonSerializer.Serialize(payload);
        var content = new StringContent(json, Encoding.UTF8, "application/json");

        try
        {
            var response = await _client.PostAsync(API_URL, content);
            var result = await response.Content.ReadAsStringAsync();

            if (response.IsSuccessStatusCode)
            {
                var data = JsonSerializer.Deserialize<JsonElement>(result);
                return data
                    .GetProperty("choices")[0]
                    .GetProperty("message")
                    .GetProperty("content")
                    .GetString() ?? "Error";
            }

            return $"Error: {response.StatusCode}";
        }
        catch (Exception e)
        {
            return $"HireIQ unavailable: {e.Message}";
        }
    }
}