using System.Text;
using System.Text.Json;

namespace HireIQ.API.Services;

public class GroqService
{
    private readonly HttpClient _client;
    private readonly string _groqKey;
    private readonly string _hireiqUrl;

    private const string GROQ_MODEL = "llama-3.3-70b-versatile";
    private const string GROQ_URL = "https://api.groq.com/openai/v1/chat/completions";

    private const string SYSTEM_PROMPT = """
You are HireIQ, an expert AI HR assistant.
You specialize in:
1. RESUME SCREENING & SCORING:
   - Analyze resume vs job description
   - Give score out of 100
   - List strengths and skill gaps
   - Give clear Shortlist/Reject decision
   - Format: ## HireIQ Evaluation, Score: X/100
2. HR CONVERSATIONS:
   - Career guidance and roadmaps
   - Skill gap analysis
   - Salary insights (India market in LPA)
   - Interview preparation tips
   - Career transition advice
3. CANDIDATE SHORTLISTING:
   - Compare multiple candidates
   - Budget-aware ranking
   - Justify your selections clearly
4. RESUME BUILDING:
   - Generate COMPLETE professional HTML resume
   - Include CSS styling inline
   - Modern layout with sidebar or header
   - Skill tags, experience bullets
   - Footer: Generated by HireIQ
   - Make it ATS-friendly
Be professional, helpful, and concise.
Only mention HireIQ when asked who you are.
Never repeatedly mention your creator in responses.
""";

    public GroqService(IConfiguration config)
    {
        _groqKey = config["GroqSettings:ApiKey"] ??
                   Environment.GetEnvironmentVariable("GROQ_API_KEY") ?? "";
        _hireiqUrl = config["HireIQSettings:BaseUrl"] ?? "";
        _client = new HttpClient();
        _client.Timeout = TimeSpan.FromSeconds(130);
    }

    // ── Chat — Groq with system prompt + history ─────────
    public async Task<string> GenerateAsync(
        string userMessage,
        List<object>? history = null)
    {
        var messages = new List<object>
        {
            new { role = "system", content = SYSTEM_PROMPT }
        };

        if (history != null)
            messages.AddRange(history.TakeLast(5));

        messages.Add(new { role = "user", content = userMessage });

        return await CallGroq(messages, maxTokens: 10000);
    }

    // ── Field/Content Generate — NO system prompt, user context only ──
    // ── GenerateFieldAsync ────────────────────────────────
    public async Task<string> GenerateFieldAsync(string prompt)
    {
        if (!string.IsNullOrEmpty(_hireiqUrl))
        {
            try
            {
                var hireiqPayload = new
                {
                    prompt,
                    max_tokens = 1024,
                    temperature = 0.7
                };
                var hireiqJson = JsonSerializer.Serialize(hireiqPayload);
                var hireiqContent = new StringContent(hireiqJson, Encoding.UTF8, "application/json");

                // ✅ HireIQ ke liye alag timeout — 120 seconds
                using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(120));
                var hireiqResponse = await _client.PostAsync(
                    $"{_hireiqUrl}/generate",
                    hireiqContent,
                    cts.Token  // ✅ cancel token pass karo
                );
                var hireiqResult = await hireiqResponse.Content.ReadAsStringAsync();

                if (hireiqResponse.IsSuccessStatusCode)
                {
                    var data = JsonSerializer.Deserialize<JsonElement>(hireiqResult);
                    var text = data.GetProperty("result").GetString() ?? "";
                    if (!string.IsNullOrWhiteSpace(text)) return text;
                }
            }
            catch (TaskCanceledException)
            {
                // ✅ Timeout — Groq pe fallback, user ko wait nahi karwao
                Console.WriteLine("HireIQ timeout — falling back to Groq");
            }
            catch { /* other errors — fallback */ }
        }

        // Groq fallback
        var messages = new List<object>
    {
        new { role = "user", content = prompt }
    };
        return await CallGroq(messages, maxTokens: 1024);
    }

    // ── Structured JSON output (Groq JSON mode) ──────────
    // Returns a strongly-typed object instead of free text — no more regex parsing.
    public async Task<T?> GenerateJsonAsync<T>(string prompt) where T : class
    {
        var messages = new List<object>
        {
            new { role = "system", content = "You are HireIQ, an expert AI HR assistant. Respond ONLY with valid JSON matching the schema described by the user. No markdown, no extra text." },
            new { role = "user", content = prompt }
        };

        var raw = await CallGroq(messages, maxTokens: 4000, jsonMode: true, temperature: 0.3);

        try
        {
            return JsonSerializer.Deserialize<T>(raw, new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true
            });
        }
        catch
        {
            return null; // caller decides fallback
        }
    }

    // ── Internal Groq Call ────────────────────────────────
    private async Task<string> CallGroq(List<object> messages, int maxTokens = 5000, bool jsonMode = false, double temperature = 0.7)
    {
        try
        {
            object payload = jsonMode
                ? new
                {
                    model = GROQ_MODEL,
                    messages,
                    max_tokens = maxTokens,
                    temperature,
                    response_format = new { type = "json_object" }
                }
                : new
                {
                    model = GROQ_MODEL,
                    messages,
                    max_tokens = maxTokens,
                    temperature
                };

            var json = JsonSerializer.Serialize(payload);
            var content = new StringContent(json, Encoding.UTF8, "application/json");

            using var request = new HttpRequestMessage(HttpMethod.Post, GROQ_URL);
            request.Headers.Add("Authorization", $"Bearer {_groqKey}");
            request.Content = content;

            var response = await _client.SendAsync(request);
            var result = await response.Content.ReadAsStringAsync();

            if (response.IsSuccessStatusCode)
            {
                var data = JsonSerializer.Deserialize<JsonElement>(result);
                return data
                    .GetProperty("choices")[0]
                    .GetProperty("message")
                    .GetProperty("content")
                    .GetString() ?? "Error";
            }

            return $"Error: {response.StatusCode}";
        }
        catch (Exception e)
        {
            return $"HireIQ unavailable: {e.Message}";
        }
    }
}