// <auto-generated />
using System;
using System.Collections.Generic;
using HireIQ.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HireIQ.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260627164955_Phase2HiringAutomation")]
    partial class Phase2HiringAutomation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HireIQ.Domain.Entities.AiObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Agent")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("agent");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("latency_ms");

                    b.Property<string>("ObservationJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("observation_json");

                    b.Property<string>("RawResponse")
                        .HasColumnType("text")
                        .HasColumnName("raw_response");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid?>("RelatedQuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_question_id");

                    b.Property<float?>("ScoreAttention")
                        .HasColumnType("real")
                        .HasColumnName("score_attention");

                    b.Property<float?>("ScoreCommunication")
                        .HasColumnType("real")
                        .HasColumnName("score_communication");

                    b.Property<float?>("ScoreConfidence")
                        .HasColumnType("real")
                        .HasColumnName("score_confidence");

                    b.Property<float?>("ScoreEmotion")
                        .HasColumnType("real")
                        .HasColumnName("score_emotion");

                    b.Property<float?>("ScoreTechnical")
                        .HasColumnType("real")
                        .HasColumnName("score_technical");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<int>("TurnIndex")
                        .HasColumnType("integer")
                        .HasColumnName("turn_index");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "Agent", "TurnIndex");

                    b.ToTable("ai_observations", (string)null);
                });

            modelBuilder.Entity("HireIQ.Domain.Entities.CandidateJourney", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicantUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("applicant_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentStage")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("current_stage");

                    b.Property<Guid>("JobApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_application_id");

                    b.Property<Guid>("JobPostingId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_posting_id");

                    b.Property<DateTime>("LastTransitionAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_transition_at");

                    b.Property<string>("StageHistoryJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("stage_history_json");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantUserId");

                    b.HasIndex("JobApplicationId")
                        .IsUnique();

                    b.HasIndex("JobPostingId", "CurrentStage");

                    b.ToTable("candidate_journeys", (string)null);
                });

            modelBuilder.Entity("HireIQ.Domain.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("conversations", (string)null);
                });

            modelBuilder.Entity("HireIQ.Domain.Entities.CustomResumeField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field_name");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field_type");

                    b.Property<string>("FieldValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field_value");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("custom_resume_fields", (string)null);
                });

            modelBuilder.Entity("HireIQ.Domain.Entities.EmailNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BodyHtml")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body_html");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("category");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTime>("QueuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("queued_at");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("recipient_email");

                    b.Property<string>("RecipientName")
                        .HasColumnType("text")
                        .HasColumnName("recipient_name");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_entity_id");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("related_entity_type");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("email_notifications", (string)null);
                });

            modelBuilder.Entity("HireIQ.Domain.Entities.EmailTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BodyTemplate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body_template");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("SubjectTemplate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_template");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("email_templates", (string)null);
                });

            modelBuilder.Entity("HireIQ.Domain.Entities.GeneratedResume", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("HtmlContent")
                        .HasColumnType("text")
                        .HasColumnName("html_content");

                    b.Property<string>("PdfUrl")
                        .HasColumnType("text")
                        .HasColumnName("pdf_url");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("generated_resumes", (string)null);
                });

            modelBuilder.Entity("HireIQ.Domain.Entities.HiringDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateJourneyId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_journey_id");

                    b.Property<DateTime?>("CandidateRespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("candidate_responded_at");

                    b.Property<string>("CandidateResponse")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("candidate_response");

                    b.Property<DateTime>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid>("DecidedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("decision");

                    b.Property<DateTime?>("JoiningDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joining_date");

                    b.Property<string>("OfferDetailsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("offer_details_json");

                    b.Property<string>("OfferLetterUrl")
                        .HasColumnType("text")
                        .HasColumnName("offer_letter_url");

                    b.Property<string>("OfferedCurrency")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("offered_currency");

                    b.Property<decimal?>("OfferedSalary")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("offered_salary");

                    b.HasKey("Id");

                    b.HasIndex("CandidateJourneyId")
                        .IsUnique();

                    b.HasIndex("DecidedBy");

                    b.ToTable("hiring_decisions", (string)null);
                });

            modelBuilder.Entity("HireIQ.Domain.Entities.HrInterview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateJourneyId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_journey_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("decision");

                    b.Property<Guid>("HirerId")
                        .HasColumnType("uuid")
                        .HasColumnName("hirer_id");

                    b.Property<string>("HirerNotes")
                        .HasColumnType("text")
                        .HasColumnName("hirer_notes");

                    b.Property<string>("MeetLink")
                        .HasColumnType("text")
                        .HasColumnName("meet_link");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CandidateJourneyId");

                    b.HasIndex("HirerId");

                    b.ToTable("hr_interviews", (string)null);
                });

            modelBuilder.Entity("HireIQ.Domain.Entities.InterviewAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("answer_text");

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("TranscriptSegmentIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("transcript_segment_ids_json");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SessionId");

                    b.ToTable("interview_answers", (string)null);
                });

            modelBuilder.Entity("HireIQ.Domain.Entities.InterviewFinalScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AggregatedReasoning")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aggregated_reasoning");

                    b.Property<float>("AttentionScore")
                        .HasColumnType("real")
                        .HasColumnName("attention_score");

                    b.Property<float>("BehavioralScore")
                        .HasColumnType("real")
                        .HasColumnName("behavioral_score");

                    b.Property<float>("CommunicationScore")
                        .HasColumnType("real")
                        .HasColumnName("communication_score");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<float>("ConfidenceScore")
                        .HasColumnType("real")
                        .HasColumnName("confidence_score");

                    b.Property<float>("OverallScore")
                        .HasColumnType("real")
                        .HasColumnName("overall_score");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("recommendation");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<float>("TechnicalScore")
                        .HasColumnType("real")
                        .HasColumnName("technical_score");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("interview_final_scores", (string)null);
                });

            modelBuilder.Entity("HireIQ.Domain.Entities.InterviewQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AskedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("asked_at");

                    b.Property<int>("QuestionOrder")
                        .HasColumnType("integer")
                        .HasColumnName("question_order");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_text");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "QuestionOrder");

                    b.ToTable("interview_questions", (string)null);
                });

            modelBuilder.Entity("HireIQ.Domain.Entities.InterviewRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AiReport")
                        .HasColumnType("text")
                        .HasColumnName("ai_report");

                    b.Property<decimal?>("AttentionScore")
                        .HasColumnType("numeric")
                        .HasColumnName("attention_score");

                    b.Property<decimal?>("BehavioralScore")
                        .HasColumnType("numeric")
                        .HasColumnName("behavioral_score");

                    b.Property<string>("CandidateEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("candidate_email");

                    b.Property<string>("CandidateName")
                        .HasColumnType("text")
                        .HasColumnName("candidate_name");

                    b.Property<Guid?>("CandidateUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_user_id");

                    b.Property<decimal?>("CommunicationScore")
                        .HasColumnType("numeric")
                        .HasColumnName("communication_score");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("numeric")
                        .HasColumnName("confidence_score");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("EmotionScore")
                        .HasColumnType("numeric")
                        .HasColumnName("emotion_score");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("FinalDecision")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("final_decision");

                    b.Property<Guid>("HirerId")
                        .HasColumnType("uuid")
                        .HasColumnName("hirer_id");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.PrimitiveCollection<List<string>>("PresetQuestions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("preset_questions");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("room_code");

                    b.Property<string>("RoomPassword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("room_password");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal?>("TechnicalScore")
                        .HasColumnType("numeric")
                        .HasColumnName("technical_score");

                    b.HasKey("Id");

                    b.HasIndex("HirerId");

                    b.HasIndex("JobId");

                    b.ToTable("interview_rooms", (string)null);
                });

            modelBuilder.Entity("HireIQ.Domain.Entities.InterviewSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AudioRecordingUrl")
                        .HasColumnType("text")
                        .HasColumnName("audio_recording_url");

                    b.Property<Guid>("CandidateJourneyId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_journey_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<Guid>("InterviewRoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("interview_room_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("TotalDurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("total_duration_seconds");

                    b.Property<string>("TranscriptUrl")
                        .HasColumnType("text")
                        .HasColumnName("transcript_url");

                    b.Property<string>("VideoRecordingUrl")
                        .HasColumnType("text")
                        .HasColumnName("video_recording_url");

                    b.HasKey("Id");

                    b.HasIndex("CandidateJourneyId");

                    b.HasIndex("InterviewRoomId");

                    b.ToTable("interview_sessions", (string)null);
                });

            modelBuilder.Entity("HireIQ.Domain.Entities.InterviewTranscript", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float?>("Confidence")
                        .HasColumnType("real")
                        .HasColumnName("confidence");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("EndMs")
                        .HasColumnType("bigint")
                        .HasColumnName("end_ms");

                    b.Property<int>("SegmentIndex")
                        .HasColumnType("integer")
                        .HasColumnName("segment_index");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Speaker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("speaker");

                    b.Property<long>("StartMs")
                        .HasColumnType("bigint")
                        .HasColumnName("start_ms");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "SegmentIndex");

                    b.ToTable("interview_transcripts", (string)null);
                });

            modelBuilder.Entity("HireIQ.Domain.Entities.JobApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApplicantUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("applicant_user_id");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<string>("CoverLetter")
                        .HasColumnType("text")
                        .HasColumnName("cover_letter");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid?>("ResumeId")
                        .HasColumnType("uuid")
                        .HasColumnName("resume_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantUserId");

                    b.HasIndex("JobId", "ApplicantUserId")
                        .IsUnique();

                    b.ToTable("job_applications", (string)null);
                });

            modelBuilder.Entity("HireIQ.Domain.Entities.JobBoardSync", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Board")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("board");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<string>("ExternalUrl")
                        .HasColumnType("text")
                        .HasColumnName("external_url");

                    b.Property<Guid>("JobPostingId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_posting_id");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.HasKey("Id");

                    b.HasIndex("JobPostingId", "Board")
                        .IsUnique();

                    b.ToTable("job_board_syncs", (string)null);
                });

            modelBuilder.Entity("HireIQ.Domain.Entities.JobDescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("job_descriptions", (string)null);
                });

            modelBuilder.Entity("HireIQ.Domain.Entities.JobPosting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BenefitsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("benefits_json");

                    b.Property<DateTime?>("ClosesAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closes_at");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("employment_type");

                    b.Property<int?>("ExperienceMaxYears")
                        .HasColumnType("integer")
                        .HasColumnName("experience_max_years");

                    b.Property<int?>("ExperienceMinYears")
                        .HasColumnType("integer")
                        .HasColumnName("experience_min_years");

                    b.Property<Guid>("HirerId")
                        .HasColumnType("uuid")
                        .HasColumnName("hirer_id");

                    b.Property<string>("IndeedExternalId")
                        .HasColumnType("text")
                        .HasColumnName("indeed_external_id");

                    b.Property<string>("LinkedInPostUrl")
                        .HasColumnType("text")
                        .HasColumnName("linkedin_post_url");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<string>("NaukriExternalId")
                        .HasColumnType("text")
                        .HasColumnName("naukri_external_id");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("RequirementsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("requirements_json");

                    b.Property<decimal?>("SalaryMax")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("salary_max");

                    b.Property<decimal?>("SalaryMin")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("salary_min");

                    b.Property<string>("SalaryPeriod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("salary_period");

                    b.Property<string>("SkillsNiceToHaveJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("skills_nice_to_have_json");

                    b.Property<string>("SkillsRequiredJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("skills_required_json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("work_mode");

                    b.HasKey("Id");

                    b.HasIndex("HirerId");

                    b.HasIndex("Status", "PublishedAt");

                    b.ToTable("job_postings", (string)null);
                });

            modelBuilder.Entity("HireIQ.Domain.Entities.MockInterviewSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AiEvaluation")
                        .HasColumnType("text")
                        .HasColumnName("ai_evaluation");

                    b.PrimitiveCollection<List<string>>("Answers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("answers_json");

                    b.Property<decimal?>("CommunicationScore")
                        .HasColumnType("numeric")
                        .HasColumnName("communication_score");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("numeric")
                        .HasColumnName("confidence_score");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("JobDescription")
                        .HasColumnType("text")
                        .HasColumnName("job_description");

                    b.Property<string>("JobTitle")
                        .HasColumnType("text")
                        .HasColumnName("job_title");

                    b.Property<decimal?>("OverallScore")
                        .HasColumnType("numeric")
                        .HasColumnName("overall_score");

                    b.PrimitiveCollection<List<string>>("Questions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("questions_json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("InProgress")
                        .HasColumnName("status");

                    b.Property<decimal?>("TechnicalScore")
                        .HasColumnType("numeric")
                        .HasColumnName("technical_score");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("mock_interview_sessions", (string)null);
                });

            modelBuilder.Entity("HireIQ.Domain.Entities.Resume", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CandidateName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("candidate_name");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileUrl")
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("resumes", (string)null);
                });

            modelBuilder.Entity("HireIQ.Domain.Entities.Template", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("BaseStructureJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("base_structure_json");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsPremium")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_premium");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PreviewImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("preview_image_url");

                    b.HasKey("Id");

                    b.ToTable("templates", (string)null);
                });

            modelBuilder.Entity("HireIQ.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ScreeningResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CandidateStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Screened")
                        .HasColumnName("candidate_status");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("HireiqAnalysis")
                        .HasColumnType("text")
                        .HasColumnName("hireiq_analysis");

                    b.Property<Guid>("JdId")
                        .HasColumnType("uuid")
                        .HasColumnName("jd_id");

                    b.Property<decimal>("MinilmScore")
                        .HasColumnType("numeric")
                        .HasColumnName("minilm_score");

                    b.Property<Guid>("ResumeId")
                        .HasColumnType("uuid")
                        .HasColumnName("resume_id");

                    b.Property<bool>("Shortlisted")
                        .HasColumnType("boolean")
                        .HasColumnName("shortlisted");

                    b.HasKey("Id");

                    b.HasIndex("JdId");

                    b.HasIndex("ResumeId");

                    b.ToTable("screening_results", (string)null);
                });

            modelBuilder.Entity("HireIQ.Domain.Entities.AiObservation", b =>
                {
                    b.HasOne("HireIQ.Domain.Entities.InterviewSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("HireIQ.Domain.Entities.CandidateJourney", b =>
                {
                    b.HasOne("HireIQ.Domain.Entities.User", "Applicant")
                        .WithMany()
                        .HasForeignKey("ApplicantUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HireIQ.Domain.Entities.JobApplication", "JobApplication")
                        .WithMany()
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HireIQ.Domain.Entities.JobPosting", "JobPosting")
                        .WithMany()
                        .HasForeignKey("JobPostingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("JobApplication");

                    b.Navigation("JobPosting");
                });

            modelBuilder.Entity("HireIQ.Domain.Entities.Conversation", b =>
                {
                    b.HasOne("HireIQ.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HireIQ.Domain.Entities.CustomResumeField", b =>
                {
                    b.HasOne("HireIQ.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HireIQ.Domain.Entities.GeneratedResume", b =>
                {
                    b.HasOne("HireIQ.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HireIQ.Domain.Entities.HiringDecision", b =>
                {
                    b.HasOne("HireIQ.Domain.Entities.CandidateJourney", "CandidateJourney")
                        .WithMany()
                        .HasForeignKey("CandidateJourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HireIQ.Domain.Entities.User", "Decider")
                        .WithMany()
                        .HasForeignKey("DecidedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CandidateJourney");

                    b.Navigation("Decider");
                });

            modelBuilder.Entity("HireIQ.Domain.Entities.HrInterview", b =>
                {
                    b.HasOne("HireIQ.Domain.Entities.CandidateJourney", "CandidateJourney")
                        .WithMany()
                        .HasForeignKey("CandidateJourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HireIQ.Domain.Entities.User", "Hirer")
                        .WithMany()
                        .HasForeignKey("HirerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CandidateJourney");

                    b.Navigation("Hirer");
                });

            modelBuilder.Entity("HireIQ.Domain.Entities.InterviewAnswer", b =>
                {
                    b.HasOne("HireIQ.Domain.Entities.InterviewQuestion", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HireIQ.Domain.Entities.InterviewSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("HireIQ.Domain.Entities.InterviewFinalScore", b =>
                {
                    b.HasOne("HireIQ.Domain.Entities.InterviewSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("HireIQ.Domain.Entities.InterviewQuestion", b =>
                {
                    b.HasOne("HireIQ.Domain.Entities.InterviewSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("HireIQ.Domain.Entities.InterviewRoom", b =>
                {
                    b.HasOne("HireIQ.Domain.Entities.User", "Hirer")
                        .WithMany()
                        .HasForeignKey("HirerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HireIQ.Domain.Entities.JobDescription", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Hirer");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("HireIQ.Domain.Entities.InterviewSession", b =>
                {
                    b.HasOne("HireIQ.Domain.Entities.CandidateJourney", "CandidateJourney")
                        .WithMany()
                        .HasForeignKey("CandidateJourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HireIQ.Domain.Entities.InterviewRoom", "InterviewRoom")
                        .WithMany()
                        .HasForeignKey("InterviewRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateJourney");

                    b.Navigation("InterviewRoom");
                });

            modelBuilder.Entity("HireIQ.Domain.Entities.InterviewTranscript", b =>
                {
                    b.HasOne("HireIQ.Domain.Entities.InterviewSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("HireIQ.Domain.Entities.JobApplication", b =>
                {
                    b.HasOne("HireIQ.Domain.Entities.User", "Applicant")
                        .WithMany()
                        .HasForeignKey("ApplicantUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HireIQ.Domain.Entities.JobDescription", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("HireIQ.Domain.Entities.JobBoardSync", b =>
                {
                    b.HasOne("HireIQ.Domain.Entities.JobPosting", "JobPosting")
                        .WithMany()
                        .HasForeignKey("JobPostingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobPosting");
                });

            modelBuilder.Entity("HireIQ.Domain.Entities.JobDescription", b =>
                {
                    b.HasOne("HireIQ.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HireIQ.Domain.Entities.JobPosting", b =>
                {
                    b.HasOne("HireIQ.Domain.Entities.User", "Hirer")
                        .WithMany()
                        .HasForeignKey("HirerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hirer");
                });

            modelBuilder.Entity("HireIQ.Domain.Entities.MockInterviewSession", b =>
                {
                    b.HasOne("HireIQ.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HireIQ.Domain.Entities.Resume", b =>
                {
                    b.HasOne("HireIQ.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ScreeningResult", b =>
                {
                    b.HasOne("HireIQ.Domain.Entities.JobDescription", "JobDescription")
                        .WithMany()
                        .HasForeignKey("JdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HireIQ.Domain.Entities.Resume", "Resume")
                        .WithMany()
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobDescription");

                    b.Navigation("Resume");
                });
#pragma warning restore 612, 618
        }
    }
}
