using HireIQ.Application.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.SignalR;

namespace HireIQ.API.Hubs;

/// <summary>
/// Real-time channel for the candidate-side AI interview UI.
/// Browser sends transcript chunks + visual frames; hub returns next question.
/// REST endpoints (AiInterviewController) handle persistence; this hub is for low-latency push.
/// </summary>
[Authorize]
public class InterviewHub : Hub
{
    private readonly IInterviewOrchestrator _orch;

    public InterviewHub(IInterviewOrchestrator orch) => _orch = orch;

    public async Task JoinSession(string sessionId)
    {
        await Groups.AddToGroupAsync(Context.ConnectionId, $"session:{sessionId}");
    }

    /// <summary>Candidate submits a chunk of transcribed speech. Hub stores it + pushes next question.</summary>
    public async Task SubmitAnswerChunk(string sessionId, string questionId, string text, long startMs, long endMs)
    {
        var sid = Guid.Parse(sessionId);
        var qid = Guid.Parse(questionId);
        await _orch.RecordAnswerAsync(sid, qid, text, startMs, endMs);

        // Next question is generated by REST `/api/ai-interview/next-question` — keep hub simple.
        await Clients.Caller.SendAsync("AnswerAcknowledged", new { questionId = qid });
    }

    public async Task SendFrame(string sessionId, string frameBase64, long frameAtMs)
    {
        var sid = Guid.Parse(sessionId);
        var bytes = Convert.FromBase64String(frameBase64);
        await _orch.RecordVisualFrameAsync(sid, bytes, frameAtMs);
    }
}
